config/routes.rb
Semistatic::Engine.routes.draw do
  get "page_view/show"

  resources :pages


end

app/models/semistatic/page.rb
module Semistatic
  class Page < ActiveRecord::Base
    attr_accessible :layout,
                    :parts_attributes,
                    :slug,
                    :template_name,
                    :title

    has_many :parts
    accepts_nested_attributes_for :parts

    validates :slug, presence: true, uniqueness: { case_sensitive: false }
    validates :title, presence: true

    # get part by its name
    # param
    # @return Part
    def part(name)
      parts.select {|p| p.name.downcase == name.to_s.downcase }.first
    end

    # Factory a page from the config
    #     Creates the attributes required by the config
    # @param String template_name
    # @param Hash options # the page configuration
    # @return Page
    def self.factory(template_name, options)
      page = new(template_name: template_name)

      options = HashWithIndifferentAccess.new(options)
      options[:parts].each do |name, attributes|
        part = page.parts.build({ name: name })
        part.options = attributes
      end

      page.save(validate: false)
      page
    end
  end
end

app/models/semistatic/part.rb
module Semistatic
  class Part < ActiveRecord::Base
    belongs_to :page
    attr_accessible :name, :value, :file

    serialize :options, Hash

    has_attached_file :file,
      styles: lambda { |attachment| attachment.instance.options[:styles] || {} }

    # attachment validation
    validates_attachment_presence :file, if: :is_file?
    validates_attachment_size :file, :less_than => 5.megabytes
    # TODO: Learn how to validate depending on the options, lambda maybe
    validates_attachment_content_type :file, content_type: ['image/jpeg', 'image/png', 'image/gif']

    validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :page_id }
    validates :page, presence: true


    # is this is an image?
    def is_image?
      type == :image
    end

    # is this a file?
    def is_file?
      is_image? || type == :file
    end

    # @return Symbol
    def type
      options[:type].to_sym if options[:type]
    end

    # force options to be a HashWithIndifferentAccess
    # @param (nil | Hash | HashWithIndifferentAccess)
    def options=(options)
      if options.respond_to? :deep_symbolize_keys
        options = options.deep_symbolize_keys
      end
      write_attribute(:options, options)
    end


    def valid_content_type
      if is_image?
         ['image/jpg', 'image/png', 'image/gif']
      else
        []
      end
    end
  end
end

app/controllers/semistatic/application_controller.rb
module Semistatic
  class ApplicationController < ActionController::Base
  end
end

app/controllers/semistatic/page_view_controller.rb
require_dependency "semistatic/application_controller"

module Semistatic
  class PageViewController < ApplicationController
    include Semistatic::Concerns::Controllers::PageViewController
  end
end

app/controllers/semistatic/pages_controller.rb
require_dependency "semistatic/application_controller"

module Semistatic
  class PagesController < ApplicationController
    include Semistatic::Concerns::Controllers::PagesController
  end
end

app/helpers/semistatic/application_helper.rb
module Semistatic
  module ApplicationHelper
  end
end

app/views/layouts/semistatic/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Semistatic</title>
  <%= stylesheet_link_tag    "semistatic/application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/semistatic/page_view/show.html.erb
<h1>PageView#show</h1>
<p>Find me in semistaticpage_view/show.html.erb</p>

app/views/semistatic/pages/_form.html.erb
<%= javascript_include_tag "semistatic/semistatic" %>
<%= tinymce %>

<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :layout %><br />
    <%= f.text_field :layout %>
  </div>


  <fieldset>
    <legend>Page Parts</legend>
    <%= f.fields_for :parts do |subform| %>
      <div class="field">
        <%= subform.label(subform.object.name) %><br />
        <%= @presenter.input(subform) %>
      </div>
    <% end %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semistatic/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/semistatic/pages/index.html.erb
<h1>Listing pages</h1>

<ul>
<% @config.pages.each do |name, config| %>
  <li><%= link_to(name.to_s.titleize, new_page_path(template_name: name)) %></li>
<% end %>
</ul>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.slug %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/semistatic/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/semistatic/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Slug:</b>
  <%= @page.slug %>
</p>

<p>
  <b>Layout:</b>
  <%= @page.layout %>
</p>


<% @page.parts.each do |part| %>
  <div class="semistatic-part">
    <h2 class="zpart-name"><%= part.name %></h2>
    <div class="content"><%= @presenter.output(part.name) %></div>
  </div>
<% end %>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>